ALTER TABLE agents
    ADD COLUMN IF NOT EXISTS storage_ok BOOLEAN NOT NULL DEFAULT FALSE AFTER webrtc_enabled,
    ADD COLUMN IF NOT EXISTS storage_total_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0 AFTER storage_ok,
    ADD COLUMN IF NOT EXISTS storage_free_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0 AFTER storage_total_bytes,
    ADD COLUMN IF NOT EXISTS recording_workers INT UNSIGNED NOT NULL DEFAULT 0 AFTER storage_free_bytes,
    ADD COLUMN IF NOT EXISTS relay_workers INT UNSIGNED NOT NULL DEFAULT 0 AFTER recording_workers,
    ADD COLUMN IF NOT EXISTS health_error VARCHAR(1000) NOT NULL DEFAULT '' AFTER relay_workers;
